### PR TITLE
Proper implementation of closeInventory

### PR DESCRIPTION
**Pull request by Lukas-Sturm**
Based on the [Spigot Documentation](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/inventory/InventoryClickEvent.html) you should not call closeInventory inside of the InventoryClickEvent. I added a proper implementation for closing the inventory.
I found a local class to be the easiest for that example.

BTW: very nice Library 👍 
Learned a lot while reading your code :)

### CODE REVIEW

**Comment by personinblack** [comment]
you are 100% right. we absolutely have to make some changes there but the way you do it is a bit dirty. if you can convert that inner (or local) class to lambda i can merge your pull request. something like this:

```java
final Element exitButton = new BasicElement(
    new ItemStack(Material.BARRIER),
    event -> {
        event.setCancelled(true);

        Bukkit.getScheduler().runTask(
            Bukkit.getPluginManager().getPlugin("myPluginsName"),
            () -> {
                event.getWhoClicked().closeInventory();
            }
        );
    }
);
```

and maybe in the future, instead of using `InventoryClickEvent`, we can create our own event and return that to the user. that way we can implement a close method of ours inside our event which does this ^^.

i really appreciate your kind words and contribution. thanks!

**Review by personinblack — CHANGES_REQUESTED** [review]
https://github.com/Personinblack/black/pull/2#issuecomment-385699560

**Comment by Lukas-Sturm** [comment]
I managed to get the wanted structure by creating a class that implements the runnable interface.
But I think adding a new class that handles the runnable stuff is not fitting your library

```
public class ScheduleSupplier implements Runnable {
    Supplier task;
    public ScheduleSupplier (Supplier task) {
        this.task = task;
    }

    @Override
    public void run() {
        task.get();
    }
}

```

Maybe that would fit the purpose of the Library more?
As you don't need to do much other than closing the inventory anyways, the rest can be done before calling the BukkitScheduler.
```
public class ProperInventoryClose implements Runnable {
    Player player;

    public ProperInventoryClose(Player player) {
        this.player = player;
    }

    @Override
    public void run() {
        player.closeInventory();
    }
}

```
(Totally no idea how to name my classes xD)

**Comment by Lukas-Sturm** [comment]
Wait, just realised that you might want to open a new inventory. That would kind of need the first approach ^^

**Comment by personinblack** [comment]
we can't have these type of stuff inside the readme. because we only need to provide simple solutions that works and looks elegant. we are not trying to provide super basic stuff for those who don't know fundamentals of java. we also are not trying to give complex examples that distracts people from the actual topic. those who are trying to use black should have enough java knowledge to understand lambdas. creating a class just for a simple bukkit task is not elegant and not suitable for this type of documentation, since it's unnecessarily complex for a simple stuff and takes the attention from the real information we are providing.

i can offer you another solution that may look better:

```java
final Element exitButton = new BasicElement(
    new ItemStack(Material.BARRIER),
    event -> {
        event.setCancelled(true);

        new BukkitRunnable(){

            @Override
            public void run() {
                event.getWhoClicked().closeInventory();
            }
        }.runTask(Bukkit.getPluginManager().getPlugin("myPluginsName"));
    }
);
```

but of course these are just my opinions and if you think i'm wrong, just tell me.

about class/object naming:

`ScheduleSupplier` as an object name is bad because it represents a profession. object's name *shouldn't* tell us what it does but what it really is. `-er` is a hint for us, any object name that ends with `-er` is most likely representing a profession and therefore bad.

`ProperInventoryClose` is also bad since it also is *not* telling us what it really is. i would use the name `InventoryCloseTask` if i ever had to create a class like this (i hope not).

this is not just about naming because the name you gave to an object or a class, control's how you define it. so if you give your object a bad name, you will try to mold it to that name's definition. if you are trying to write proper object oriented classes, always aim to name them properly.

**Comment by Lukas-Sturm** [comment]
yea, you'r right. I dont realy have an eye for the layout of my classes / if something is convenient to do that way (yet) ^^
Your solution looks good, but as you say it's not fitting the pourpose of black :)
Maybe we shouldn't change it, or just give a hint that that isn't the savest way to close a inventory.

**Comment by personinblack** [comment]
that would be better (at least till i do the custom event thingy). we can do something like this:

```java
// this is just a list, nothing fancy or
// relevant to the topic.
final List<Element> playerHeads =
    new PlayerHeads(PlayerType.STAFF);

final Element exitButton = new BasicElement(
    new ItemStack(Material.BARRIER),
    event -> {
        event.setCancelled(true);
        // this is not how you should close your inventory.
        // please do read here: https://github.com/Personinblack/black/pull/2
        event.getWhoClicked.closeInventory();
    }
);
```

you can edit your pull request or i can just push a commit with this change, choice is yours. thanks ;)

**Review by personinblack — APPROVED** [review]

**Comment by Lukas-Sturm** [comment]
me casually hiding my typo and the fact that i have no idea how to revert a commit 😅

**Pull request merged**
